### ISSUE TITLE
Error while parsing

### ISSUE THREAD

**Issue by Elmekior** [Pantheonal/FC-Fetcher#1]
Hello, 

So I have an error when I tried to install and launch the cron.php job from my local server.

Here is the error

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\FC-Fetcher-master\lib\api.php on line 1887

Fatal error: Call to a member function getName() on a non-object in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\FC-Fetcher-master\cron.php on line 39

This can happen at any moment during the execution of the job. (I can be at 50 member found and it will crash or it will go further.

This seem to be the offending code bit : 

 // Dirty temp fix
            foreach($String as $i => $s)
            {
                if (stripos($s, '(') !== false)
                {
                    $server = $s;
                    $name = $String[$i - 1];
                }
            }

I added a ini_set('max_execution_time', 3000); so it has more than enough time to parse.

Please help me :)

**Comment by Pantheonal** [comment]
It could be that Lodestone went under maintenance half way through the fetch. This would cause it to fail when it gets to a character and it can't fetch the data.

If this is still failing could you show me the contents of your config.php (obviously obscure the database bits). The bit of code is to do with the API, not with the fetcher itself.

You can also set the debug like to true and run the cron through the browser to see what sort of error you're getting after a while.

**Comment by Elmekior** [comment]
Here is the content of my config.php, I am still using my easyphp localhot
web so I can show you this.

<?php
// Used for misc debug output
$debug = true;
// Database information
$db_server = "127.0.0.1";
$db_user = "root";
$db_pass = "";
$db_database = "123";
$db_port = ""; // can be left blank if default (3306)
// Default number of members per page
$perPage = 30;
// Fetch the id below from Lodestone :
http://na.finalfantasyxiv.com/lodestone/freecompany/9232379236109517808/
$fc_id = "9234349560946526924";
// Add translation below, example ($classes_fr...)
$classes_en =
array("gladiator","pugilist","marauder","lancer","archer","rogue","conjurer","thaumaturge","arcanist","carpenter","blacksmith","armorer","goldsmith","leatherworker","weaver","alchemist","culinarian","miner","botanist","fisher");
$classes = $classes_en;
$classimg =
array("images/gladiator.png","images/pugilist.png","images/marauder.png","images/lancer.png","images/archer.png","images/rogue.png","images/conjurer.png","images/thaumaturge.png","images/arcanist.png","images/carpenter.png","images/blacksmith.png","images/armorer.png","images/goldsmith.png","images/leatherworker.png","images/weaver.png","images/alchemist.png","images/culinarian.png","images/miner.png","images/botanist.png","images/fisher.png");
?>


I don'T get any other error than this one and I don't think the lodestone
is in maintenance since I can fetch some members. It really does just stop
at a random place.

Also, apparently that I needed to laugh the program cron job more than one
because it kept getting further each time.

**Comment by Pantheonal** [comment]
Could you paste the debug output from cron.php (you don't need to include all of it, just a couple of entries before the fault, and then the fault itself)?

At this point it sounds like it may be a caching issue with your local dev environment.
