### ISSUE TITLE
Align center

### ISSUE THREAD

**Issue by emendrael** [Pantheonal/FC-Fetcher#2]
Hi Pantheonal, 

First, good job for this amazing script. My FC loves it !

I've used it here, but as you can see, it's not centered : http://crossxroads.fr/roster.php

Do you have any idea of how i could center it ? my knowledge in php/html is quite low ^^;

Thanks a lot 

Emen Dra'el @Moogle

**Comment by Pantheonal** [comment]
Hi Emen,

Thanks!

For whatever reason this is outputting at the bottom of your page, and 
not in the container for the content.

You could wrap the entire page in <center></center> tags, or try to 
include the code in the actual content wrapper (I assume this is 
Wordpress, that would mean making it a static page and using a PHP 
plugin or other methods to include the code in the page content).

I stopped using a plugin and hard-coded it to my theme for the 
Wordpress. You can do this by finding your themes functions.php (usually 
in wp-content/themes/*****/functions.php), and enter this code at the 
bottom:

function phpinclude_func( $atts , $content = null ) {
     if ( !is_null( $content ) && file_exists( ABSPATH . '../' . $content ) )
         include( ABSPATH . '../' . $content );
     else
         echo "File not found.";
}
add_shortcode( 'phpinclude', 'phpinclude_func' );


Then, simply add a page called "Roster" (Nos Members?), and add the 
following:
[phpinclude]{location of roster.php}/roster.php[/phpinclude]

Either of these should set you straight :).

Good luck,
Jack

**Comment by emendrael** [comment]
You're to kind to answer so fast :)

Thanks :+1: 

I tried the very first method, and it worked perfectly, as you can see here : http://crossxroads.fr/roster.php

So, thank you a lot (and seriously, i shall learn php a little, i could have found myself)

**Comment by emendrael** [comment]
You're to kind to answer so fast :)

Thanks :+1:

I tried the very first method, and it worked perfectly, as you can see here : http://crossxroads.fr/roster.php

So, thank you a lot (and seriously, i shall learn php a little, i could have found myself)
